### ISSUE TITLE
Server crash on query

### ISSUE THREAD

**Issue by aknarts** [ctdk/goiardi#52] opened 2017-07-13 15:54 UTC
Hi, when I run `knife status --hide-by-mins 3600`

The server crashes with:
```
goiardi[6526]: panic: runtime error: index out of range
goiardi[6526]: goroutine 5487 [running]:
goiardi[6526]: github.com/ctdk/goiardi/indexer.(*IdxDoc).TextSearch(0xc42000fb80, 0x0, 0x0, 0xc422078700, 0x0, 0x0)
goiardi[6526]:         /Users/jeremy.bingham/go/src/github.com/ctdk/goiardi/indexer/file_index.go:474 +0x34c
goiardi[6526]: github.com/ctdk/goiardi/indexer.(*IdxCollection).searchTextCollection.func1(0x0, 0x0, 0xc426dabe60, 0xc426dabec0
goiardi[6526]:         /Users/jeremy.bingham/go/src/github.com/ctdk/goiardi/indexer/file_index.go:330 +0x5a
goiardi[6526]: created by github.com/ctdk/goiardi/indexer.(*IdxCollection).searchTextCollection
goiardi[6526]:         /Users/jeremy.bingham/go/src/github.com/ctdk/goiardi/indexer/file_index.go:344 +0x252
systemd[1]: goiardi.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
systemd[1]: goiardi.service: Unit entered failed state.
systemd[1]: goiardi.service: Failed with result 'exit-code'.
```

This is happening for quite some time, I did an upgrade today to the latest release hoping this would be resolved. Guess I should have reported it sooner.

I am happy to provide any info required and debug this further.

**Comment by ctdk** [comment] 2017-07-13 16:52
Thanks for the heads up, I've successfully duplicated the bug with the postgresql search, which tells me that it's just all around busted. Somehow I was totally unaware of this functionality in knife (*hangs head in shame*), and the `chef-pedant` tests never caught this.

I have to fix another issue with the API anyway, so hopefully I'll have this turned around soon along with that.

**Comment by ctdk** [comment] 2017-07-13 23:28
OK, I know exactly what the problem is - it's the NOT combined with a range query. Ironically, I just went and fixed a bunch of cases with the search where NOT was breaking and I noticed that NOT with range queries wasn't working correctly. I couldn't find any evidence it was being used at all, though, so I didn't worry about it.

Shows what I know, I guess.

**Comment by aknarts** [comment] 2017-07-20 12:19
If you have a branch or commit that I can test it on I am happy to do so. And you are doing great job, your project is way easier to use than the official server(and uses way less resources).

**Comment by ctdk** [comment] 2017-08-10 17:00
The wheels turn slowly, but they do turn. (This one was extra complicated because it involved a lot of slogging around with the search parser grammar and fiddling with the methods in the parser as well, which is pretty complicated.) There's a branch I've pushed up at https://github.com/ctdk/goiardi/tree/not-range-search that, while not ready for a release yet, does have various search related changes including a fix for the `NOT [start TO end]` issue.

Right now it's spewing out a ton of debug log statements, doesn't handle unicode properly, and needs tests run against it, but it's OK to test the above case. I hope to have it cleaned up soon, and to make a release once I get that memory hemorrhaging issue @rmoriz brought to my attention cleared up (at least to some extent). 

Thanks for the kind words and your patience.

**Comment by ctdk** [comment] 2017-09-12 16:09
FYI, there's a branch in https://github.com/ctdk/goiardi/tree/0.11.6-merging that's in pre-release testing that fixes this issue. Apologies for the slow going; I've had a beastly commute for the last several months.

**Comment by aknarts** [comment] 2018-01-06 11:31
Hey, I believe 0.11.6 fixes both of my issues here, but sadly there are no packages built(I can build it from source but that would break the deployment process). Is it possible to either build the 0.11.6 packages and/or release how you build them so that the packages end up identical?

**Comment by ctdk** [comment] 2018-01-18 16:10
@aknarts As mentioned in another issue, the wheels are at last turning again (I've had the unfortunate combination of "being quite busy" and "not feeling well at all" lately, which has had a definite impact on my extracurricular activities). I'll get binaries built for the latest prerelease, and if you look in `packaging/packaging.sh` you'll see how I build goiardi and package it. (You could run the script yourself, of course, but then you'd be building a bunch of extra packages and architectures you probably don't need.)

The real release should be soon, in any case, assuming nothing pops up in testing or a breaking bug is brought to my attention before it's done.

**Comment by ctdk** [comment] 2018-01-28 23:22
Also merged to master and released.

**Closed by ctdk** 2018-01-28 23:22 UTC
